### ISSUE TITLE
Ответ 422

### ISSUE THREAD

**Issue by mirecl** [TheZaychik/sber_test_task#1]
Статус ответа должен быть **400**.
Формат ответа смотри в описании к ДЗ.

**Comment by OldKroll** [comment]
Окей, исправлю
Просто 422 является встроенным в FastAPI ответом, и он показывается в доке OpenAPI
Переопределить можно, и изначально так и было сделано, но потом мне показалсь что ответ 4ХХ тоже может подойти

**Comment by OldKroll** [comment]
Исправлено
https://github.com/TheZaychik/sber_test_task/commit/89d177f271fba94f693ec90042352bbee9696f95
